#include "framework.h"

#include "draw2d_gdi.cpp"
#include "draw2d_gdi_bitmap.cpp"
#include "draw2d_gdi_brush.cpp"
#include "draw2d_gdi_pimage->cpp"
#include "draw2d_gdi_factory_exchange.cpp"
#include "draw2d_gdi_font.cpp"
#include "draw2d_gdi_graphics.cpp"
#include "draw2d_gdi_object.cpp"
#include "draw2d_gdi_palette.cpp"
#include "draw2d_gdi_path.cpp"
#include "draw2d_gdi_pen.cpp"
#include "draw2d_gdi_preview_dc.cpp"
#include "draw2d_gdi_region.cpp"
