rmdir /s /q "V:\votagus\basis\time\intermediate\basis"
rmdir /s /q "V:\votagus\basis\time\library\basis"
rmdir /s /q "V:\votagus\basis\app\stage\x86"
rmdir /s /q "V:\votagus\basis\app\stage\x64"
rmdir /s /q "V:\votagus\basis\time\ccvotagus\Release"
rmdir /s /q "V:\votagus\basis\app\stage\x86\ccvotagus\Release"
rmdir /s /q "V:\votagus\basis\app\stage\x64\ccvotagus\Release"
rmdir /s /q "V:\votagus\basis\app\stage\"
