rmdir /s /q "V:\store\basis\time\intermediate\basis"
rmdir /s /q "V:\store\basis\time\library\basis"
rmdir /s /q "V:\store\basis\app\stage\x86"
rmdir /s /q "V:\store\basis\app\stage\x64"
rmdir /s /q "V:\store\basis\time\store\Release"
rmdir /s /q "V:\store\basis\app\stage\x86\store\Release"
rmdir /s /q "V:\store\basis\app\stage\x64\store\Release"
rmdir /s /q "V:\store\basis\app\stage\"
