rmdir /s /q "T:\stage\time\intermediate\basis"
rmdir /s /q "T:\stage\time\library\basis"
rmdir /s /q "T:\stage\time\ccvotagus\Release"
rmdir /s /q "T:\stage\stage\x86"
rmdir /s /q "T:\stage\stage\x64"
rmdir /s /q "T:\stage\stage\"